apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    petronova.io/team: {{ .Values.team | quote }}
    petronova.io/data-classification: {{ .Values.dataClassification | quote }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurity }}
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
