name: OT-Data
parent: $folder_ids:teams
iam_by_principals:
  $iam_principals:pn-data-team:
    - roles/viewer
  $iam_principals:pn-ot-engineering:
    - roles/viewer
  $iam_principals:pn-auditors:
    - roles/iam.securityReviewer
    - roles/viewer
