{{- range .Values.secretStores }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .projectID }}
      # Uses the ESO controller's Workload Identity (no key files)
---
{{- end }}
